sudo: false
addons:
  apt:
    packages:
      - xvfb
      - gnome-keyring
      - libgnome-keyring-dev
services:
  - mongodb
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - iojs
  - "0.12"
  - "0.10"
before_install:
  - npm i -g npm@^2.0.0
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc
before_script:
  - npm prune
