sudo: false
language: node_js
cache:
  directories:
  - node_modules
notifications:
  email: false
services:
  - mongodb
node_js:
  - 4
  - "0.12"
  - "0.10"
before_install: |
  npm update -g npm
  echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc
before_script:
  - npm prune
after_success:
  - npm run semantic-release